function buildPlaylistJSON() {
    return {
        "name":document.getElementById("titleInput").value + " (GCP Generated)",
        "description":document.getElementById("descriptionInput").value + " (Playlist automatically generated by GCP, http://www.webgcp.com)"
    }
}
function buildTrackJSON() {
    return {
        "uris": trackURIs
    }
}