function buildPlaylistJSON() {
    return {
        "name":document.getElementById("titleInput").value + " (GCP Generated)",
        "description":document.getElementById("descriptionInput").value + "Playlist generated by GCP, link: ..."
    }
}
function buildTrackJSON() {
    return {
        "uris": trackURIs
    }
}